name: inkrement
favicon: null
layout_spectrum: 0.25454
typography_spectrum: 0.5962708969600499
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010300'
    - '#e2f6ca'
    - '#17579a'
    - '#2cc1c1'
    - '#8e8259'
  brandStrength: 0.5625
  lightness: 0.05466053611598909
  saturation: 0.8125
  rhythmicContrast: 0.9656356167979538
purpose: []
